### PR TITLE
Changes to createURLString function

### PR DESCRIPTION
**Pull request by TruePadawan**
The second condition of the 'if' statement in the function will be true if the length of the value associated with the key 'backgroundColor' is '6', if the value was 'yellow' or any other 6 letter color then it would be True which is wrong so I used a function that checks if a value is a hex instead

### CODE REVIEW

**Review by cyberboysumanjay — APPROVED** [review]
Changes looks good

**Review by TruePadawan — COMMENTED** [review]
Neat

**Comment by TruePadawan** [comment]
How do i get the changes merged to the main branch. This is the first time I'm contributing

**Comment by TruePadawan** [comment]
Why hasn't the changes been merged?

**Pull request merged**
